---
# Services
# First level array represent a group.
# Leave only a "items" key if not using group (group name, icon & tagstyle are optional, section separation will not be displayed).
services:
  - name: "Services"
    icon: []
    items:
      - name: "Blog"
        logo: "assets/blog.png"
        subtitle: "Blog Posts"
        tag: ""
        url: "https://matzradloff.info"
      - name: "qBittorrent"
        logo: "assets/qbit.png"
        subtitle: "Web-UI for Torrents"
        tag: ""
        url: "https://qbt.matzradloff.info"
  - name: "Plex"
    icon: []
    items:
      - name: "Plex"
        logo: "assets/plex.png"
        subtitle: "Plex Media Server Frontend"
        tag: ""
        url: "https://plex.matzradloff.info"
      - name: "Tautulli"
        logo: "assets/tautulli.png"
        subtitle: "Monitor Plex + Stats"
        tag: ""
        url: "http://127.0.0.1:8181/home"
      - name: "Ombi"
        logo: "assets/ombi.png"
        subtitle: "Request TV & Movies for Plex"
        tag: ""
        url: "http://127.0.0.1:5000/"
      - name: "Sonarr"
        logo: "assets/sonarr.png"
        subtitle: "Automatically download TV Shows for Plex"
        tag: ""
        url: "http://sonarr.matzradloff.info"
      - name: "Radarr"
        logo: "assets/radarr.png"
        subtitle: "Automatically download Movies for Plex"
        tag: ""
        url: "http://radarr.matzradloff.info"
      - name: "Jackett"
        logo: "assets/jackett.png"
        subtitle: "Manage trackers for Sonarr + Radarr"
        tag: ""
        url: "https://jackett.matzradloff.info"
